.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. asacoin_qt test_asacoin_qt
clean: FORCE
	$(MAKE) -C .. asacoin_qt_clean test_asacoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_asacoin_qt_check
asacoin-qt asacoin-qt.exe: FORCE
	 $(MAKE) -C .. asacoin_qt
