#!/bin/bash

# This is a thin wrapper around asacoin-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using asacoin-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_ASACOIND

# Grab the value of $REAL_ASACOINCLI which may be asacoin-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_ASACOINCLI}" "$@" | sed 's/\r//'
